# Generated by Django 3.2.5 on 2021-07-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('intelligence', models.IntegerField(default=1, verbose_name='Интеллект')),
                ('wits', models.IntegerField(default=1, verbose_name='Сообразительность')),
                ('resolve', models.IntegerField(default=1, verbose_name='Решительность')),
                ('strength', models.IntegerField(default=1, verbose_name='Сила')),
                ('dexterity', models.IntegerField(default=1, verbose_name='Ловкость')),
                ('stamina', models.IntegerField(default=1, verbose_name='Выносливость')),
                ('presence', models.IntegerField(default=1, verbose_name='Влияние')),
                ('manipulation', models.IntegerField(default=1, verbose_name='Манипуляция')),
                ('composure', models.IntegerField(default=1, verbose_name='Самообладание')),
                ('athletics', models.IntegerField(default=0, verbose_name='Атлетика')),
                ('size', models.IntegerField(default=5, verbose_name='Размер')),
                ('speed_factor', models.IntegerField(default=0, verbose_name='Фактор скорости')),
                ('perception_boost', models.IntegerField(default=0, verbose_name='Бонус к восприятию')),
                ('health', models.IntegerField(default=0, verbose_name='Всего здоровья')),
                ('bashing', models.IntegerField(default=0, verbose_name='Тупой урон')),
                ('lethal', models.IntegerField(default=0, verbose_name='Летальный урон')),
            ],
        ),
        migrations.CreateModel(
            name='Uratha',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.human')),
                ('aggravated', models.IntegerField(default=0, verbose_name='Аггравированный урон')),
                ('supernatural_tolerance', models.IntegerField(default=1, verbose_name='Сверхъестественное отклонение')),
                ('essence_current_value', models.IntegerField(default=0, verbose_name='Текущее значение эссенции')),
                ('essence_max_value', models.IntegerField(default=0, verbose_name='Максимальное значение эссенции')),
                ('willpower_current_value', models.IntegerField(default=0, verbose_name='Текущее значение силы воли')),
                ('willpower_max_value', models.IntegerField(default=0, verbose_name='Максимальное значение силы воли')),
                ('intelligence_bonus', models.IntegerField(default=0, verbose_name='Бонус к интеллект')),
                ('wits_bonus', models.IntegerField(default=0, verbose_name='Бонус к сообразительность')),
                ('resolve_bonus', models.IntegerField(default=0, verbose_name='Бонус к решительность')),
                ('strength_bonus', models.IntegerField(default=0, verbose_name='Бонус к сила')),
                ('dexterity_bonus', models.IntegerField(default=0, verbose_name='Бонус к ловкость')),
                ('stamina_bonus', models.IntegerField(default=0, verbose_name='Бонус к выносливость')),
                ('presence_bonus', models.IntegerField(default=0, verbose_name='Бонус к влияние')),
                ('manipulation_bonus', models.IntegerField(default=0, verbose_name='Бонус к манипуляция')),
                ('composure_bonus', models.IntegerField(default=0, verbose_name='Бонус к самообладание')),
                ('auspice', models.IntegerField(choices=[('0', 'Undefined'), ('1', 'Cahalith'), ('2', 'Elodoth'), ('3', 'Irraka'), ('4', 'Ithaeur'), ('5', 'Rahu')], default='0', verbose_name='Покровительство')),
                ('tribe', models.IntegerField(choices=[('0', 'Undefined'), ('1', 'Bloodtalons'), ('2', 'Boneshadows'), ('3', 'Hunterindarkness'), ('4', 'Ironmasters'), ('5', 'Stormlords'), ('6', 'Ghostwolves')], default='0', verbose_name='Племя')),
                ('harmony', models.IntegerField(default=0, verbose_name='Гармония')),
                ('current_form', models.IntegerField(choices=[('0', 'Undefined'), ('1', 'Hishu'), ('2', 'Dalu'), ('3', 'Gauru'), ('4', 'Urshul'), ('5', 'Urhan')], default='0', verbose_name='Текущая форма')),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.human',),
        ),
    ]
