# Generated by Django 3.2.5 on 2021-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uratha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('auspice', models.IntegerField(choices=[('1', 'Cahalith'), ('2', 'Elodoth'), ('3', 'Irraka'), ('4', 'Ithaeur'), ('5', 'Rahu')], verbose_name='Покровительство')),
                ('tribe', models.IntegerField(choices=[('1', 'Bloodtalons'), ('2', 'Boneshadows'), ('3', 'Hunterindarkness'), ('4', 'Ironmasters'), ('5', 'Stormlords'), ('6', 'Ghostwolves')], verbose_name='Племя')),
                ('health', models.IntegerField(verbose_name='Здоровье')),
                ('willpower', models.IntegerField(verbose_name='Сила воли')),
                ('primal_urge', models.IntegerField(verbose_name='Древний зов')),
                ('essence', models.IntegerField(verbose_name='Эссенция')),
                ('harmony', models.IntegerField(verbose_name='Гармония')),
                ('current_form', models.IntegerField(verbose_name='Гармония')),
            ],
        ),
    ]
