# Generated by Django 3.2.5 on 2021-07-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uratha',
            name='current_form',
            field=models.IntegerField(choices=[('1', 'Hishu'), ('2', 'Dalu'), ('3', 'Gauru'), ('4', 'Urshul'), ('5', 'Urhan')], verbose_name='Текущая форма'),
        ),
    ]
